default-task = 'build'
version = 0.1

extensions = ['chomp@0.1:swc', 'chomp@0.1:jspm', 'chomp@0.1:npm']

[template-options.npm]
auto-install = true

[[task]]
name = 'build'
deps = ['ts', 'jsx', 'html']

[[task]]
name = 'ts'
dep = 'src/#.ts'
target = 'lib/#.js'
template = 'swc'

[[task]]
name = 'jsx'
dep = 'src/#.tsx'
target = 'lib/#.js'
template = 'swc'
[task.template-options.config]
'jsc.parser.tsx' = true
'jsc.transform.react.pragma' = 'h'


[[task]]
name = 'html'
deps = ['src/#.html', 'npm:install']
engine = 'node'
invalidation = 'always'
target = 'lib/#.html'
run = '''
    import { Generator } from '@jspm/generator';
    import { readFile, writeFile } from 'fs/promises';
    import { pathToFileURL } from 'url';
    import mkdirp from 'mkdirp';
    import { dirname } from 'path';

    const generator = new Generator({
      mapUrl: pathToFileURL(process.env.TARGET),
      env: ["browser", "production"], 
      defaultProvider: 'jspm.cachefly'
    });

    const htmlSource = await readFile(process.env.DEP, 'utf-8');

    mkdirp.sync(dirname(process.env.TARGET));
    await writeFile(process.env.TARGET, await generator.htmlInject(htmlSource, {
      htmlUrl: pathToFileURL('process.env.TARGET'),
      preload: true,
      integrity: true,
      whitespace: true,
      esModuleShims: true,
      comment: true,
      trace: true
    }));
'''